inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'coverage/**/*'
    - 'public/**/*'
    - 'log/**/*'
    - 'tmp/**/*'

Style/FrozenStringLiteralComment:
  Enabled: false